import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "en" | "ru";

const translations = {
  en: {
    // Auth
    welcomeBack: "Welcome back",
    createAccount: "Create your account",
    continueWithGoogle: "Continue with Google",
    or: "or",
    emailAddress: "Email address",
    password: "Password",
    signIn: "Sign in",
    signUp: "Sign up",
    createAccountBtn: "Create account",
    loading: "Loading...",
    testMode: "Continue without login (Test Mode)",
    noAccount: "Don't have an account?",
    haveAccount: "Already have an account?",
    language: "Language",

    // Dashboard
    goodMorning: "Good morning",
    goodAfternoon: "Good afternoon",
    goodEvening: "Good evening",
    goodNight: "Good night",
    dailyHealthScore: "Daily Health Score",
    steps: "Steps",
    heartRate: "Heart Rate",
    sleep: "Sleep",
    calories: "Calories",
    restingAvg: "Resting avg",
    burnedToday: "Burned today",
    goal: "Goal",
    score: "Score",
    labResults: "Lab Results",
    uploadAnalyze: "Upload & analyze blood work",
    activity: "Activity",
    nutrition: "Nutrition",
    habits: "Habits",
    dailyQuote: "Daily Wisdom",
    quickActions: "Quick Actions",
    water: "Water",
    workout: "Workout",
    yoga: "Yoga",
    vitamins: "Vitamins",
    logged: "Logged!",

    // Bottom Nav
    home: "Home",
    aiCoach: "AI Coach",
    labs: "Labs",
    profile: "Profile",
    notes: "Notes",
    addNote: "Add Note",
    editNote: "Edit Note",
    noteTitle: "Title",
    noteContent: "Content",
    todoList: "To-Do",
    notesList: "Notes",
    noNotes: "No notes yet",
    deleteNote: "Delete",
    markComplete: "Done",
    markIncomplete: "Not done",

    // Nutrition
    trackMeals: "Track your meals & macros",
    addFood: "Add Food",
    addManual: "Add Manually",
    takePhoto: "Take Photo",
    dailyLimitExceeded: "Daily calorie limit exceeded",
    exceededBy: "You've exceeded your limit by",
    approachingLimit: "Approaching calorie limit",
    remaining: "remaining for today",
    weeklyTrends: "Weekly Trends",
    avgDaily: "avg daily",
    todaysMeals: "Today's Meals",
    noMeals: "No meals logged yet",
    saveMeal: "Save Meal",
    updateEntry: "Update Entry",
    foodName: "Food name",
    mealType: "Meal type",
    portionSize: "Portion size",
    breakfast: "Breakfast",
    lunch: "Lunch",
    dinner: "Dinner",
    snack: "Snack",
    calorieSettings: "Calorie Settings",
    dailyCalorieLimit: "Daily Calorie Limit",
    autoCalculated: "Auto (calculated from profile)",
    manualInput: "Manual input",
    kcal: "kcal",
    save: "Save",
    cancel: "Cancel",
    protein: "Protein",
    carbs: "Carbs",
    fat: "Fat",

    // Habits
    buildRoutines: "Build healthy daily routines",
    todaysProgress: "Today's Progress",
    completed: "completed",
    bestStreak: "Best streak",
    days: "days",
    newHabit: "New Habit",
    editHabit: "Edit Habit",
    habitName: "Name",
    dailyTarget: "Daily Target",
    unit: "Unit (optional)",
    category: "Category",
    icon: "Icon",
    addHabit: "Add Habit",
    updateHabit: "Update Habit",
    configureQuickActions: "Choose quick actions",
    selectUpTo: "Select up to",
    deleteHabit: "Delete",

    // Activity
    trackMovement: "Track your movement & workouts",
    weeklySteps: "Weekly Steps",
    todaysWorkouts: "Today's Workouts",
    min: "min",

    // Lab Results
    uploadBloodWork: "Upload blood work for AI-powered analysis",
    uploadLabResults: "Upload lab results PDF or photo",
    bloodWorkTypes: "Blood work, metabolic panels, CBC, etc.",
    analyzingResults: "Analyzing your lab results...",
    readingBiomarkers: "Reading biomarkers & interpreting values",
    summary: "Summary",
    areasOfConcern: "Areas of Concern",
    biomarkers: "Biomarkers",
    recommendations: "Recommendations",
    previousResults: "Previous Results",
    analyzed: "Analyzed",
    failed: "Failed",
    processing: "Processing...",
    close: "Close",

    // Coach
    personalAssistant: "Your personal health assistant",
    howCanIHelp: "How can I help you today?",
    askAbout: "Ask me about workouts, nutrition, sleep, or wellness",
    askCoach: "Ask your AI coach...",
    createWorkoutPlan: "Create a beginner workout plan",
    improveSleep: "How can I improve my sleep?",
    highProteinMeals: "Healthy high-protein meal ideas",
    stretchesForDesk: "Best stretches for desk workers",
    savedSessions: "Saved Sessions",
    newChat: "New Chat",
    noSavedSessions: "No saved sessions yet",
    saveChat: "Save Chat",
    deleteSession: "Delete",

    // Profile
    signOut: "Sign out",
    displayName: "Display Name",
    yourName: "Your name",
    bodyMetrics: "Body Metrics",
    age: "Age",
    gender: "Gender",
    male: "Male",
    female: "Female",
    other: "Other",
    height: "Height",
    weight: "Weight",
    activityLevel: "Activity Level",
    sedentary: "Sedentary (little/no exercise)",
    light: "Light (1-3 days/week)",
    moderate: "Moderate (3-5 days/week)",
    active: "Active (6-7 days/week)",
    veryActive: "Very Active (intense daily)",
    healthGoals: "Health Goals",
    loseWeight: "Lose weight",
    gainMuscle: "Gain muscle",
    improveSleepGoal: "Improve sleep",
    increaseEndurance: "Increase endurance",
    eatHealthier: "Eat healthier",
    reduceStress: "Reduce stress",
    buildFlexibility: "Build flexibility",
    saveProfile: "Save Profile",
    saving: "Saving...",
    themeSettings: "Theme Settings",
    autoSunrise: "Auto (sunrise/sunset)",
    autoHours: "Auto (by hours)",
    manualTheme: "Manual",
    lightFrom: "Light from",
    lightTo: "to",
    locationDetected: "Location detected",
    locationNotDetected: "Location not detected, using hours",
    detectLocation: "Detect location",
  },
  ru: {
    // Auth
    welcomeBack: "С возвращением",
    createAccount: "Создайте аккаунт",
    continueWithGoogle: "Войти через Google",
    or: "или",
    emailAddress: "Email адрес",
    password: "Пароль",
    signIn: "Войти",
    signUp: "Регистрация",
    createAccountBtn: "Создать аккаунт",
    loading: "Загрузка...",
    testMode: "Продолжить без входа (Тест)",
    noAccount: "Нет аккаунта?",
    haveAccount: "Уже есть аккаунт?",
    language: "Язык",

    // Dashboard
    goodMorning: "Доброе утро",
    goodAfternoon: "Добрый день",
    goodEvening: "Добрый вечер",
    goodNight: "Доброй ночи",
    dailyHealthScore: "Дневной показатель здоровья",
    steps: "Шаги",
    heartRate: "Пульс",
    sleep: "Сон",
    calories: "Калории",
    restingAvg: "В покое",
    burnedToday: "Сожжено сегодня",
    goal: "Цель",
    score: "Оценка",
    labResults: "Анализы",
    uploadAnalyze: "Загрузить и проанализировать",
    activity: "Активность",
    nutrition: "Питание",
    habits: "Привычки",
    dailyQuote: "Мудрость дня",
    quickActions: "Быстрые действия",
    water: "Вода",
    workout: "Тренировка",
    yoga: "Йога",
    vitamins: "Витамины",
    logged: "Записано!",

    // Bottom Nav
    home: "Главная",
    aiCoach: "AI Тренер",
    labs: "Анализы",
    profile: "Профиль",
    notes: "Заметки",
    addNote: "Добавить",
    editNote: "Редактировать",
    noteTitle: "Заголовок",
    noteContent: "Содержание",
    todoList: "Задачи",
    notesList: "Заметки",
    noNotes: "Пока нет заметок",
    deleteNote: "Удалить",
    markComplete: "Готово",
    markIncomplete: "Не готово",

    // Nutrition
    trackMeals: "Отслеживайте питание и макросы",
    addFood: "Добавить еду",
    addManual: "Добавить вручную",
    takePhoto: "Сфотографировать",
    dailyLimitExceeded: "Превышен дневной лимит калорий",
    exceededBy: "Вы превысили лимит на",
    approachingLimit: "Приближение к лимиту калорий",
    remaining: "осталось на сегодня",
    weeklyTrends: "Недельные тренды",
    avgDaily: "в среднем в день",
    todaysMeals: "Приёмы пищи",
    noMeals: "Нет записей о еде",
    saveMeal: "Сохранить",
    updateEntry: "Обновить",
    foodName: "Название блюда",
    mealType: "Приём пищи",
    portionSize: "Размер порции",
    breakfast: "Завтрак",
    lunch: "Обед",
    dinner: "Ужин",
    snack: "Перекус",
    calorieSettings: "Настройки калорий",
    dailyCalorieLimit: "Дневной лимит калорий",
    autoCalculated: "Авто (рассчитано из профиля)",
    manualInput: "Ввести вручную",
    kcal: "ккал",
    save: "Сохранить",
    cancel: "Отмена",
    protein: "Белки",
    carbs: "Углеводы",
    fat: "Жиры",

    // Habits
    buildRoutines: "Формируйте здоровые привычки",
    todaysProgress: "Прогресс за сегодня",
    completed: "выполнено",
    bestStreak: "Лучшая серия",
    days: "дней",
    newHabit: "Новая привычка",
    editHabit: "Редактировать",
    habitName: "Название",
    dailyTarget: "Дневная цель",
    unit: "Единица (необяз.)",
    category: "Категория",
    icon: "Иконка",
    addHabit: "Добавить",
    updateHabit: "Обновить",
    configureQuickActions: "Выберите быстрые действия",
    selectUpTo: "Выберите до",
    deleteHabit: "Удалить",

    // Activity
    trackMovement: "Отслеживайте движение и тренировки",
    weeklySteps: "Шаги за неделю",
    todaysWorkouts: "Тренировки за сегодня",
    min: "мин",

    // Lab Results
    uploadBloodWork: "Загрузите анализы для AI-интерпретации",
    uploadLabResults: "Загрузить PDF или фото анализов",
    bloodWorkTypes: "Анализ крови, биохимия, ОАК и т.д.",
    analyzingResults: "Анализируем результаты...",
    readingBiomarkers: "Читаем биомаркеры и интерпретируем",
    summary: "Резюме",
    areasOfConcern: "Проблемные области",
    biomarkers: "Биомаркеры",
    recommendations: "Рекомендации",
    previousResults: "Предыдущие результаты",
    analyzed: "Проанализировано",
    failed: "Ошибка",
    processing: "Обработка...",
    close: "Закрыть",

    // Coach
    personalAssistant: "Ваш персональный AI-тренер",
    howCanIHelp: "Чем могу помочь?",
    askAbout: "Спросите о тренировках, питании, сне или здоровье",
    askCoach: "Спросите AI тренера...",
    createWorkoutPlan: "Составь план тренировок для начинающих",
    improveSleep: "Как улучшить сон?",
    highProteinMeals: "Идеи блюд с высоким содержанием белка",
    stretchesForDesk: "Лучшие упражнения для офисных работников",
    savedSessions: "Сохранённые сессии",
    newChat: "Новый чат",
    noSavedSessions: "Нет сохранённых сессий",
    saveChat: "Сохранить чат",
    deleteSession: "Удалить",

    // Profile
    signOut: "Выйти",
    displayName: "Имя",
    yourName: "Ваше имя",
    bodyMetrics: "Параметры тела",
    age: "Возраст",
    gender: "Пол",
    male: "Мужской",
    female: "Женский",
    other: "Другой",
    height: "Рост",
    weight: "Вес",
    activityLevel: "Уровень активности",
    sedentary: "Сидячий (мало/нет упражнений)",
    light: "Лёгкий (1-3 дня/неделю)",
    moderate: "Умеренный (3-5 дней/неделю)",
    active: "Активный (6-7 дней/неделю)",
    veryActive: "Очень активный (интенсивно каждый день)",
    healthGoals: "Цели здоровья",
    loseWeight: "Похудеть",
    gainMuscle: "Набрать мышцы",
    improveSleepGoal: "Улучшить сон",
    increaseEndurance: "Увеличить выносливость",
    eatHealthier: "Питаться здоровее",
    reduceStress: "Снизить стресс",
    buildFlexibility: "Развить гибкость",
    saveProfile: "Сохранить профиль",
    saving: "Сохранение...",
    themeSettings: "Настройки темы",
    autoSunrise: "Авто (восход/закат)",
    autoHours: "Авто (по часам)",
    manualTheme: "Вручную",
    lightFrom: "Светлая с",
    lightTo: "до",
    locationDetected: "Местоположение определено",
    locationNotDetected: "Местоположение не определено, по часам",
    detectLocation: "Определить",
  },
} as const;

type Translations = Record<string, string>;

type LanguageContextType = {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: Translations;
};

const LanguageContext = createContext<LanguageContextType>({
  language: "en",
  setLanguage: () => {},
  t: translations.en,
});

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    return (localStorage.getItem("app-language") as Language) || "en";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("app-language", lang);
  };

  const t = translations[language];

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
